# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='location', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Description default text'),
        ),
    ]
